// <auto-generated />
namespace MedicalExamination.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addforce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addforce));
        
        string IMigrationMetadata.Id
        {
            get { return "202003162121399_Add-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
